server:
  port: 8761
     
spring:
  cloud:
    config:
      server:
        git:
          uri: file:/c:/config-repo
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
  server:
    waitTimeInMsWhenSyncEmpty: 0
  instance:
    preferIpAddress: true